### ISSUE TITLE
does not install on laravel 5.2

### ISSUE THREAD

**Issue by ikender** [boxfrommars/rutorika-laravel-html#1]
nevermind about my initial issue, found the 5.2 branch, still having issues installing

  [Symfony\Component\Debug\Exception\FatalErrorException]
  Class 'Rutorika\Html\HtmlServiceProvider' not found

does not seem to be installing the vendor files

**Comment by boxfrommars** [comment]
@ikender 
Before composer install you should delete 'Rutorika\Html\HtmlServiceProvider' string from your config/app.php providers. Then do install and then add the provider back. 
But this package is in early beta, so I advise you not to use this package

**Comment by ikender** [comment]
@boxfrommars 
Yeah, I had tried with the line and without it... when i don't have it the only message I get is "nothing to install or update"

**Comment by ikender** [comment]
so, to install on Laravel 5.2 you need the following in your composer.json file

```
    "require": {
        "php": ">=5.5.9",
        "laravel/framework": "5.2.*",
        "rutorika/laravel-html": "dev-laravel-5.2 as 0.0.1"
    },
    "repositories": [
        {
            "type": "git",
            "url": "https://github.com/boxfrommars/rutorika-laravel-html.git"
        }
    ],

```
